#!/bin/bash
if [ "$#" -ne 2 ]
then
  echo "please provide a folder and a mode between 1 and 4"
  exit 1
fi
cg="cg.yml"
./callGraph/callGraph $1 -language 'm' -noShow -ymlOut $cg 
rakudo -I ./modules/ do.raku\  $( grealpath $1) $cg "DEMO/add.m 
DEMO/multiply.m" $2
 #"$(git -C $1 diff --name-only HEAD HEAD~1)"
#matlab run_all_tests.m
#octave run_all_tests.m


 