success=moxunit_runtests('./',...
                         '-with_coverage',...
                         '-cover','/path/with/code',...
                         '-cover_xml_file','coverage.xml',...
                         '-cover_html_dir','coverage_html');